app-type: debian-package

build-image: dockerregistry.test.netflix.net:7002/engtools/newt-c-builder/xenial:latest

build-setup:
  - >
    sudo apt-get update && sudo apt-get install -y
    libogg-dev
    python-setuptools
    python-tk
    python-dev
    ffmpeg
  - sudo easy_install pip
  - sudo pip install --upgrade pip
  - sudo pip install --upgrade h5py
  - sudo pip install --upgrade numpy scipy matplotlib pandas nose
  - sudo pip install --upgrade scikit-learn scikit-image
  - sudo pip install --upgrade openpyxl
  - sudo pip install --upgrade sureal

build-step:
  
  # ==== make and install vmafossexec and models ====
  - make clean
  - make
  - sudo make install
  - make testlib

  # ==== External ffmpeg path ====
  - touch $(pwd)/python/src/vmaf/externals.py
  - echo "FFMPEG_PATH = '/usr/bin/ffmpeg'" > $(pwd)/python/src/vmaf/externals.py

  # ==== tests ====
  - cd python; export PYTHONPATH=$(pwd)/src:$PYTHONPATH; python -m unittest discover -t . -s test/lib -p '*_libtest.py'
  - cd python; export PYTHONPATH=$(pwd)/src:$PYTHONPATH; python -m unittest discover -t . -s test -p '*_test.py'
  - cd python; export PYTHONPATH=$(pwd)/src:$PYTHONPATH; python -m unittest discover -t . -s test/extra -p '*_extratest.py'

  # ==== create necessary folders ====
  - mkdir -p $(pwd)/newt_pkg/apps/transcoder/bin
  - mkdir -p $(pwd)/newt_pkg/apps/transcoder/lib/pkgconfig
  - mkdir -p $(pwd)/newt_pkg/usr/local/lib/
  - mkdir -p $(pwd)/newt_pkg/usr/local/include/
  - mkdir -p $(pwd)/newt_pkg/usr/local/share/model

  # ==== copy necessary folders/files ====

  # ==== copy libvmaf files ====
  - cp $(pwd)/wrapper/libvmaf.pc $(pwd)/newt_pkg/apps/transcoder/lib/pkgconfig
  - cp $(pwd)/wrapper/libvmaf.a $(pwd)/newt_pkg/usr/local/lib
  - cp $(pwd)/wrapper/src/libvmaf.h $(pwd)/newt_pkg/usr/local/include

  # ==== copy model files to: /usr/local/share/model ====
  - cp -r $(pwd)/model/* $(pwd)/newt_pkg/usr/local/share/model

package-root: "newt_pkg"
