language: python
python:
  - "2.7"
  - "3.6"

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8" CC="gcc-4.8"
  - sudo apt-get install git

install:
  - pip install tox-travis

script:
  - make
  - sudo make install
  - make testlib
  - tox -c python/ -- -v -p no:warnings -m 'main or lib'
