image: Visual Studio 2017
configuration: Release

build:
  project: vmaf.sln

after_build: 7z a vmaf-win-x64.zip x64\Release\*.*

artifacts:
    - path: vmaf-win-x64.zip
    - path: x64\Release\*.*

deploy:
  - provider: GitHub
    artifacts: vmaf-win-x64.zip,x64\Release\examples.bat,x64\Release\libvmaf.lib,x64\Release\vmafossexec.exe,x64\Release\vmaf.exe
    auth_token:
      secure: 'hY5Mk6KOwgQ97TzEBsM7Woqr1ZIm5QTvHg8EvxMV1x8j3wk/3mNBMqWFFbEIBK0i'
    prerelease: true
    on:
      appveyor_repo_tag: true
